# Generated by Django 3.2.9 on 2021-11-30 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllExcelFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_field', models.CharField(max_length=200)),
                ('second_field', models.CharField(max_length=200)),
                ('third_field', models.CharField(max_length=200)),
            ],
        ),
    ]
