# Generated by Django 3.2.9 on 2021-11-30 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AllExcelFiles',
            new_name='AllExcelFile',
        ),
    ]
